-- AlterTable
ALTER TABLE "Territory" ALTER COLUMN "chakra" DROP NOT NULL,
ALTER COLUMN "chakra" DROP DEFAULT,
ALTER COLUMN "health" DROP DEFAULT,
ALTER COLUMN "lastActive" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "password" TEXT NOT NULL DEFAULT '',
ALTER COLUMN "xp" DROP DEFAULT,
ALTER COLUMN "faction" DROP DEFAULT;
